version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: reboot2024
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: password
    ports:
      - "5000:5000"